### ISSUE TITLE
Image insertion

### ISSUE THREAD

**Issue by imkaywu** [bogoli/-folio#10]
I found that the origin line in markdown doesn't work so well
`![drawing](drawing.jpg)`

and if I use 
```
<div class="img_row">
	<img class="col two" src="/assets/img/research/transform/right2left.png">
</div>
```
some parts of the image is cut off.

I was wondering if there is any resizing issue with the image.

**Comment by bogoli** [comment]
The images don't get resized, they're cropped to fit the template.

**Comment by imkaywu** [comment]
Is there a way to resize the image instead, which files should I change? thanks.

**Comment by bogoli** [comment]
You'll want to edit the SASS files. 
`_layout.scss` contains the code for the images. You might want to start by removing the line  `overflow:hidden;` in the `img_row` class.
