### ISSUE TITLE
Issues with adding Bootstrap CDN

### ISSUE THREAD

**Issue by merama** [bogoli/-folio#12]
Hello,

Thank you for the amazing theme. I am trying to add bootstrap CDN in head. I want to add some of the in-built styles of Bootstrap. But when I do that, the style of portfolio changes completely [screenshot](https://postimg.org/image/90slbawad7/). I had added following line of code. 
`<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">`
I was wondering if you could provide guidance on how to resolve this.

**Comment by bogoli** [comment]
Hi -- looks like Bootstrap might be overriding some of the styles of the theme. I haven't worked with Bootstrap before, so I can't really help you on this. Sorry!
