### ISSUE TITLE
Footer text doesn't wrap on mobile

### ISSUE THREAD

**Issue by robinmetral** [bogoli/-folio#17]
The footer text doesn't wrap when the width becomes smaller than the content. Or maybe it does but has a fixed height.

Ubuntu/Firefox

Do you take PRs?

**Comment by bogoli** [comment]
Hadn't noticed the lack of wrapping! PR= pull request? If so then yes.

**Comment by robinmetral** [comment]
Yes!
I'll work on it and send you a pull request :slightly_smiling_face:

**Comment by robinmetral** [comment]
Loving the theme by the way!

**Comment by bogoli** [comment]
Awesome, thank you! I haven't maintained this one for a while, so this is great.

**Comment by robinmetral** [comment]
Nice! :slightly_smiling_face:
