### ISSUE TITLE
How can I remove the "blog" ?

### ISSUE THREAD

**Issue by nimafazeli** [bogoli/-folio#23]
Hi, 
I am using an adapted version of your theme and I really like the way it looks.
However, I do not have a blog and for the moment I do not plan to have one. I could not figure out how to remove the blog from the navigation bar.
I tried: 
```yml
exclude: ['blog', '_posts']
```
in my `_config.yml` but it did not work. How can I proceed?

Thanks

**Comment by bogoli** [comment]
Hi @nimafazeli -- You can remove this from the menu in the header.html file. Just remove the following line (should be line 9).
` <a class="page-link" href="{{ site.baseurl }}/">blog</a>`

Sorry for the delay! I don't actively maintain this theme.
