### ISSUE TITLE
Center image thumbnail in portfolio main page

### ISSUE THREAD

**Issue by jamiemkass** [bogoli/-folio#3]
Hello. Love the theme. Is there any way to easily customize how the thumbnail image is centered in the portfolio main page? Thanks.

**Comment by bogoli** [comment]
Hi Jamie,

There's not really an easy way to keep the picture centered. I made the
decision to crop somewhat arbitrarily because it saves work on your end.
Otherwise, you'd have to make thumbnails for each project. This way, it's
also fairly responsive across different screen sizes.

I can send you some tutorials on how to do it yourself, if you're
interested.

Please let me know if there's anything else I can help with, and thanks for
using my theme!

Lia

On Wed, Oct 7, 2015 at 16:34 Jamie M. Kass notifications@github.com wrote:

> Hello. Love the theme. Is there any way to easily customize how the
> thumbnail image is centered in the portfolio main page? Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bogoli/-folio/issues/3.
> 
> ## 
> 
> Lia Bogoev

liabogoev.com
(435) 890 9695

**Comment by jamiemkass** [comment]
Lia,

Yeah, I think I'd like to make thumbnails, because I want to show (for example) a mouse face instead of his back. Could you link me to one of those tutorials? Thanks for responding so quickly!

Jamie

**Comment by bogoli** [comment]
Hi Jamie,

I think something like this would work:
https://css-tricks.com/quick-css-trick-how-to-center-an-object-exactly-in-the-center/

The class that you'd want to muck around with is the thumbnail class within
_layout.scss. You'll probably also want to crop the thumbnail pictures
themselves to be 230x230 px.

Hope that works out for you!
Lia

On Thu, Oct 8, 2015 at 6:58 AM Jamie M. Kass notifications@github.com
wrote:

> Lia,
> 
> Yeah, I think I'd like to make thumbnails, because I want to show (for
> example) a mouse face instead of his back. Could you link me to one of
> those tutorials? Thanks for responding so quickly!
> 
> Jamie
> 
> > On Oct 7, 2015, at 9:01 PM, Lia Bogoev notifications@github.com wrote:
> > 
> > Hi Jamie,
> > 
> > There's not really an easy way to keep the picture centered. I made the
> > decision to crop somewhat arbitrarily because it saves work on your end.
> > Otherwise, you'd have to make thumbnails for each project. This way, it's
> > also fairly responsive across different screen sizes.
> > 
> > I can send you some tutorials on how to do it yourself, if you're
> > interested.
> > 
> > Please let me know if there's anything else I can help with, and thanks
> > for
> > using my theme!
> > 
> > Lia
> > 
> > On Wed, Oct 7, 2015 at 16:34 Jamie M. Kass notifications@github.com
> > wrote:
> > 
> > > Hello. Love the theme. Is there any way to easily customize how the
> > > thumbnail image is centered in the portfolio main page? Thanks.
> > > 
> > > ―
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/bogoli/-folio/issues/3.
> > > 
> > > ## 
> > > 
> > > Lia Bogoev
> > 
> > liabogoev.com
> > (435) 890 9695
> > ―
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bogoli/-folio/issues/3#issuecomment-146504336.
> 
> ## 
> 
> Lia Bogoev

liabogoev.com
(435) 890 9695

**Comment by jamiemkass** [comment]
Thanks, Lia! I resized to 230x230, changed the width in thumbnail img to
230px, and fiddled with the positioning to get what I wanted.

-J

On 9 October 2015 at 10:27, Lia Bogoev notifications@github.com wrote:

> Hi Jamie,
> 
> I think something like this would work:
> 
> https://css-tricks.com/quick-css-trick-how-to-center-an-object-exactly-in-the-center/
> 
> The class that you'd want to muck around with is the thumbnail class within
> _layout.scss. You'll probably also want to crop the thumbnail pictures
> themselves to be 230x230 px.
> 
> Hope that works out for you!
> Lia
> 
> On Thu, Oct 8, 2015 at 6:58 AM Jamie M. Kass notifications@github.com
> 
> wrote:
> 
> > Lia,
> > 
> > Yeah, I think I'd like to make thumbnails, because I want to show (for
> > example) a mouse face instead of his back. Could you link me to one of
> > those tutorials? Thanks for responding so quickly!
> > 
> > Jamie
> > 
> > > On Oct 7, 2015, at 9:01 PM, Lia Bogoev notifications@github.com
> > > wrote:
> > > 
> > > Hi Jamie,
> > > 
> > > There's not really an easy way to keep the picture centered. I made the
> > > decision to crop somewhat arbitrarily because it saves work on your
> > > end.
> > > Otherwise, you'd have to make thumbnails for each project. This way,
> > > it's
> > > also fairly responsive across different screen sizes.
> > > 
> > > I can send you some tutorials on how to do it yourself, if you're
> > > interested.
> > > 
> > > Please let me know if there's anything else I can help with, and thanks
> > > for
> > > using my theme!
> > > 
> > > Lia
> > > 
> > > On Wed, Oct 7, 2015 at 16:34 Jamie M. Kass notifications@github.com
> > > wrote:
> > > 
> > > > Hello. Love the theme. Is there any way to easily customize how the
> > > > thumbnail image is centered in the portfolio main page? Thanks.
> > > > 
> > > > ―
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/bogoli/-folio/issues/3.
> > > > 
> > > > ## 
> > > > 
> > > > Lia Bogoev
> > > 
> > > liabogoev.com
> > > (435) 890 9695
> > > ―
> > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bogoli/-folio/issues/3#issuecomment-146504336.
> > 
> > ## 
> > 
> > Lia Bogoev
> 
> liabogoev.com
> (435) 890 9695
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bogoli/-folio/issues/3#issuecomment-146886615.

## 

Jamie Kass
PhD Student, Biology
Anderson Lab http://web.sci.ccny.cuny.edu/~anderson/, City College, NYC
