### ISSUE TITLE
Favicon location

### ISSUE THREAD

**Issue by simoneduca** [bogoli/-folio#7]
Hi thanks for this great simple theme.
Quick question: I can't find the lightning favicon.
Could you point me to it please?

**Comment by bogoli** [comment]
Hi,

Glad you're liking the theme! The cheatsheet for all the Font Awesome Icons can be found [here](https://fortawesome.github.io/Font-Awesome/cheatsheet/).

The lightning icon you're looking for might be called **fa-bolt**

Good luck!

**Comment by simoneduca** [comment]
Sorry my bad, needed to refresh cache. thanks
